name: Get Diagnostics From TypeScript

on:
  push:
    branches: [master]

jobs:
  get_diagnostics:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.G_ACCESS_TOKEN }}
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8
      - run: pnpm install
      - name: Download Diagnostics
        run: pnpm run new-diagnostics
      - name: Generate Diagnostics & Fixes
        run: pnpm run generate
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_options: '-n'
          commit_message: 'chore(gh-action-bot): adding new diagnostics'
          branch: ${{ github.head_ref }}
