name: Smoke Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Runs the CLI Smoke Test
    runs-on: ubuntu-latest
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: rehearsal-js
          repo: smoke-test
          github_token: ${{ secrets.SMOKE_TEST_SECRET }}
          github_user: lynchbomb
          workflow_file_name: run-smoke-test.yml
          ref: master
