name: Smoke Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-and-lint:
    name: Runs the CLI Smoke Test
    runs-on: ubuntu-latest
    steps:
      - uses: convictional/trigger-workflow-and-wait
        with:
          owner: lynchbomb
          repo: rehearsal-js/smoke-test
          github_token: ${{ secrets.SMOKE_TEST_SECRET }}
          workflow_file_name: run-smoke-test.yml
          ref: master
