name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-and-lint:
    name: Runs Test Suite with Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: volta-cli/action@v1
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.12.1
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm test
