name: CI

on:
  push:
    branches: [master, 'lynchbomb/*']
  pull_request:
    branches: [master, 'lynchbomb/*']

jobs:
  test-and-lint:
    name: Runs Test Suite with Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn install
      - run: yarn test
        with:
          node-version: 16
      - run: yarn lint
